import Phaser from 'phaser';
import { CLASS_DATA, DESKS, GAME, type Direction, type StudentSave } from '../constants/game';
import { input } from '../services/input';
import { saveStudent } from '../services/save';
interface Actor extends Phaser.Physics.Arcade.Sprite{studentName?:string;gender?:'ชาย'|'หญิง';}
export class Classroom extends Phaser.Scene{private save!:StudentSave;private player!:Actor;private npcs:Actor[]=[];private obstacles!:Phaser.Physics.Arcade.StaticGroup;private dialogue!:HTMLDivElement;private tablet!:HTMLDivElement;private menu!:HTMLDivElement;private nearestNpc:Actor|null=null;private autoSave=0;constructor(){super('Classroom');}init(data:{save?:StudentSave}):void{this.save=data.save!;}create():void{if(!this.save){this.scene.start('Title');return;}input.clearHandlers();this.createWorld();this.createActors();this.bindUi();this.createControls();this.updateHud();if(this.save.firstVisit){this.save.firstVisit=false;saveStudent(this.save);this.time.delayedCall(300,()=>this.say('ครู',`สวัสดี ${this.save.name}! ยินดีต้อนรับสู่ห้องภาษาอังกฤษ ${this.save.room}`));}}update(_t:number,dt:number):void{const dir=input.direction();const speed=GAME.playerSpeed;this.player.setVelocity(0);if(dir){this.player.setVelocity(dir==='left'?-speed:dir==='right'?speed:0,dir==='up'?-speed:dir==='down'?speed:0);this.player.setVelocity(this.player.body.velocity.normalize().scale(speed));this.player.anims.play(`${this.save.gender==='หญิง'?'girl':'boy'}-${dir}`,true);this.save.direction=dir;}else{this.player.anims.stop();this.player.setFrame(this.idleFrame(this.save.gender,this.save.direction));}this.save.x=Phaser.Math.Clamp(this.player.x,38,GAME.width-38);this.save.y=Phaser.Math.Clamp(this.player.y,48,GAME.height-42);this.autoSave+=dt;if(this.autoSave>5000){this.autoSave=0;saveStudent(this.save);}this.nearestNpc=this.findNearestNpc();this.updatePrompt();}
private createWorld():void{const k=this.save.room==='ป.2/2'?'classroom2':'classroom1';this.add.image(0,0,k).setOrigin(0).setDisplaySize(GAME.width,GAME.height);this.physics.world.setBounds(18,18,GAME.width-36,GAME.height-36);this.obstacles=this.physics.add.staticGroup();for(const [x,y] of DESKS.slice(0,16)){const o=this.obstacles.create(x,y-10,'schoolBoy',0) as Phaser.Physics.Arcade.Sprite;o.setVisible(false).setSize(58,18).setOffset(7,22).refreshBody();}for(const [x,y,w,h] of [[408,22,780,28],[408,602,780,28],[20,312,28,560],[796,312,28,560]] as const){const o=this.obstacles.create(x,y,'schoolBoy',0) as Phaser.Physics.Arcade.Sprite;o.setVisible(false).setSize(w,h).refreshBody();}}
private createActors():void{const texture=this.save.gender==='หญิง'?'schoolGirl':'schoolBoy';this.player=this.physics.add.sprite(this.save.x,this.save.y,texture,this.idleFrame(this.save.gender,this.save.direction)) as Actor;this.player.gender=this.save.gender;this.player.setScale(.9).setDepth(300);this.player.setCollideWorldBounds(true);this.player.body.setSize(24,24).setOffset(8,22);this.physics.add.collider(this.player,this.obstacles);this.cameras.main.setBounds(0,0,GAME.width,GAME.height).startFollow(this.player,true,.08,.08);this.npcs=[];CLASS_DATA[this.save.room].forEach((name,i)=>{const [x,y]=DESKS[i]??[408,260];const female = i % 3 === 0; const g: 'ชาย'|'หญิง' = female ? 'หญิง' : 'ชาย';const npc=this.physics.add.sprite(x,y-32,g==='หญิง'?'schoolGirl':'schoolBoy',this.idleFrame(g,'down')) as Actor;npc.gender=g;npc.studentName=name;npc.setScale(.9).setDepth(200+i);npc.body.setSize(22,22).setOffset(8,22);npc.setImmovable(true);this.physics.add.collider(npc,this.obstacles);this.npcs.push(npc);});}
private bindUi():void{this.dialogue=document.getElementById('dialogue') as HTMLDivElement;this.tablet=document.getElementById('tablet') as HTMLDivElement;this.menu=document.getElementById('game-menu') as HTMLDivElement;const bind=(id:string,event:string,handler:()=>void)=>{const el=document.getElementById(id);if(!el||el.dataset.bound==='1')return;el.dataset.bound='1';el.addEventListener(event,handler);};bind('tablet-btn','click',()=>this.openTablet());bind('menu-btn','click',()=>this.openMenu());bind('dialogue-next','click',()=>this.dialogue.classList.remove('show'));bind('tablet-close','click',()=>this.tablet.classList.remove('show'));bind('menu-close','click',()=>this.menu.classList.remove('show'));bind('menu-save','click',()=>saveStudent(this.save));bind('menu-title','click',()=>{saveStudent(this.save);this.scene.start('Title');});bind('email-send','click',()=>{const s=document.getElementById('email-status');if(s)s.textContent='ช่องทางส่งอีเมลถูกเตรียมไว้สำหรับ multiplayer/cloud phase';});}
private createControls():void{input.init();input.on('a',()=>this.interact());input.on('b',()=>this.closeOverlays());input.on('start',()=>this.openMenu());}
private interact():void{if(this.dialogue.classList.contains('show')||this.tablet.classList.contains('show')||this.menu.classList.contains('show'))return;if(this.nearestNpc){this.say(this.nearestNpc.studentName||'นักเรียน',this.lineFor(this.nearestNpc.studentName||''));return;}if(Phaser.Math.Distance.Between(this.player.x,this.player.y,710,180)<100)this.openTablet();}
private say(name:string,text:string):void{const n=document.getElementById('dialogue-name');const t=document.getElementById('dialogue-text');if(n)n.textContent=name;if(t)t.textContent=text;this.dialogue.classList.add('show');}
private lineFor(name:string):string{const l=['Hi! Are you ready for English?','I like learning new words.','Can you find the classroom objects?','Let’s study together!','The teacher has a new activity today.'];return l[name.length%l.length];}
private findNearestNpc():Actor|null{let b:Actor|null=null,d0=GAME.interactionDistance;for(const n of this.npcs){const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,n.x,n.y);if(d<d0){d0=d;b=n;}}return b;}
private updatePrompt():void{const p=document.getElementById('interaction-prompt');if(!p)return;if(this.nearestNpc){p.textContent='A  พูดคุย';p.classList.add('show');}else if(Phaser.Math.Distance.Between(this.player.x,this.player.y,710,180)<100){p.textContent='A  เปิด Tablet';p.classList.add('show');}else p.classList.remove('show');}
private openTablet():void{this.tablet.classList.add('show');}private openMenu():void{this.menu.classList.add('show');}private closeOverlays():void{this.dialogue.classList.remove('show');this.tablet.classList.remove('show');this.menu.classList.remove('show');}private updateHud():void{const h=document.getElementById('player-hud');if(h)h.textContent=`${this.save.room} • ${this.save.name} • XP ${this.save.xp} • LV ${this.save.level}`;}private idleFrame(g:'ชาย'|'หญิง',d:Direction):number{const r=g==='ชาย'?{down:0,left:9,right:18,up:27}:{down:0,left:9,right:18,up:27};return r[d];}}
